"""
xGEMS Template Generator
========================
Creates base template structure for GEMS3K/xGEMS input files.

This module defines the system components, phases, and solver settings
for thermodynamic equilibrium calculations of cement-based materials.

Based on GEMS3K input format specifications.

Author: Thermodynamic Modeling Project
Date: December 27, 2025
"""

import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import config


class GEMSTemplate:
    """Template generator for GEMS3K input files."""
    
    def __init__(self):
        """Initialize the GEMS template."""
        self.temperature_k = config.TEMPERATURE_K
        self.pressure_bar = config.TOTAL_PRESSURE_BAR
        self.system_components = config.SYSTEM_COMPONENTS
        
    def get_independent_components(self):
        """
        Define independent components (elements) in the system.
        
        Returns:
        --------
        list : List of independent component symbols
        """
        return self.system_components
    
    def get_phase_list(self):
        """
        Define phases to consider in equilibrium calculations.
        
        Based on Cemdata18 database phases relevant for cement systems.
        
        Returns:
        --------
        dict : Dictionary of phase categories and their phases
        """
        phases = {
            'aqueous': [
                'aqueous_solution'  # Main aqueous phase
            ],
            'gas': [
                'CO2_gas',
                'H2O_vapor'
            ],
            'solid_silicates': [
                # C-S-H phases
                'CSH_0.67',   # C-S-H with Ca/Si = 0.67
                'CSH_1.00',   # C-S-H with Ca/Si = 1.0
                'CSH_1.25',   # C-S-H with Ca/Si = 1.25
                'CSH_1.50',   # C-S-H with Ca/Si = 1.5
                'CSH_1.67',   # C-S-H with Ca/Si = 1.67
                'Silica_gel', # Amorphous silica
                'Quartz',     # Crystalline SiO2
            ],
            'solid_carbonates': [
                'Calcite',    # CaCO3
                'Aragonite',  # CaCO3 polymorph
                'Vaterite',   # CaCO3 polymorph
                'Magnesite',  # MgCO3
                'Dolomite',   # CaMg(CO3)2
            ],
            'solid_hydroxides': [
                'Portlandite',    # Ca(OH)2
                'Brucite',        # Mg(OH)2
                'Gibbsite',       # Al(OH)3
            ],
            'solid_aluminates': [
                'C3AH6',          # Hydrogarnet
                'C4AH13',         # Calcium aluminate hydrate
                'C2AH8',          # Calcium aluminate hydrate
                'Ettringite',     # AFt phase
                'Monosulfate',    # AFm phase
                'Hemicarbonate',  # AFm carbonate
                'Monocarbonate',  # AFm carbonate
            ],
            'solid_others': [
                'Gypsum',         # CaSO4·2H2O
                'Anhydrite',      # CaSO4
                'Hydrotalcite',   # Mg-Al layered double hydroxide
            ],
        }
        
        return phases
    
    def get_all_phases_flat(self):
        """
        Get all phases as a flat list.
        
        Returns:
        --------
        list : All phase names
        """
        phases_dict = self.get_phase_list()
        all_phases = []
        for category, phase_list in phases_dict.items():
            all_phases.extend(phase_list)
        return all_phases
    
    def get_solver_options(self):
        """
        Get solver configuration options.
        
        Returns:
        --------
        dict : Solver options
        """
        options = {
            'max_iterations': 1000,
            'convergence_tolerance': 1e-8,
            'activity_model': 'extended_debye_huckel',  # For aqueous phase
            'gas_model': 'ideal',  # Ideal gas assumption
            'allow_metastable': False,  # Only stable phases
        }
        return options
    
    def generate_input_header(self, mix_id, description=''):
        """
        Generate input file header.
        
        Parameters:
        -----------
        mix_id : str
            Unique mix identifier
        description : str
            Optional description
            
        Returns:
        --------
        str : Header text
        """
        header = f"""# GEMS3K Input File
# Generated by xGEMS Template Generator
# Mix ID: {mix_id}
# Description: {description}
# Temperature: {self.temperature_k} K ({self.temperature_k - 273.15}°C)
# Pressure: {self.pressure_bar} bar

"""
        return header
    
    def generate_system_definition(self):
        """
        Generate system definition section.
        
        Returns:
        --------
        str : System definition text
        """
        components = self.get_independent_components()
        
        text = "# SYSTEM DEFINITION\n"
        text += f"n_components: {len(components)}\n"
        text += "components:\n"
        for comp in components:
            text += f"  - {comp}\n"
        text += "\n"
        
        return text
    
    def generate_phases_definition(self):
        """
        Generate phases definition section.
        
        Returns:
        --------
        str : Phases definition text
        """
        phases = self.get_phase_list()
        all_phases = self.get_all_phases_flat()
        
        text = "# PHASES DEFINITION\n"
        text += f"n_phases: {len(all_phases)}\n"
        text += "phases:\n"
        
        for category, phase_list in phases.items():
            text += f"  # {category}\n"
            for phase in phase_list:
                text += f"  - {phase}\n"
        
        text += "\n"
        return text
    
    def generate_conditions_section(self, temperature_k=None, pressure_bar=None):
        """
        Generate thermodynamic conditions section.
        
        Parameters:
        -----------
        temperature_k : float, optional
            Temperature in Kelvin (default from config)
        pressure_bar : float, optional
            Pressure in bar (default from config)
            
        Returns:
        --------
        str : Conditions text
        """
        T = temperature_k if temperature_k is not None else self.temperature_k
        P = pressure_bar if pressure_bar is not None else self.pressure_bar
        
        text = "# THERMODYNAMIC CONDITIONS\n"
        text += f"temperature_K: {T}\n"
        text += f"pressure_bar: {P}\n"
        text += "\n"
        
        return text
    
    def generate_bulk_composition_template(self):
        """
        Generate bulk composition template (to be filled with actual values).
        
        Returns:
        --------
        str : Bulk composition template
        """
        components = self.get_independent_components()
        
        text = "# BULK COMPOSITION (moles)\n"
        text += "bulk_composition:\n"
        for comp in components:
            text += f"  {comp}: 0.000000\n"  # Placeholder
        text += "\n"
        
        return text
    
    def generate_gas_phase_template(self):
        """
        Generate gas phase template.
        
        Returns:
        --------
        str : Gas phase template
        """
        text = "# GAS PHASE\n"
        text += "gas_phase:\n"
        text += "  enabled: true\n"
        text += "  CO2_fraction: 0.0  # Volume fraction\n"
        text += "  N2_fraction: 1.0   # Volume fraction\n"
        text += "  total_pressure_bar: 1.01325\n"
        text += "\n"
        
        return text
    
    def generate_solver_options_section(self):
        """
        Generate solver options section.
        
        Returns:
        --------
        str : Solver options text
        """
        options = self.get_solver_options()
        
        text = "# SOLVER OPTIONS\n"
        text += "solver:\n"
        for key, value in options.items():
            text += f"  {key}: {value}\n"
        text += "\n"
        
        return text
    
    def generate_full_template(self, mix_id='TEMPLATE', description=''):
        """
        Generate complete input file template.
        
        Parameters:
        -----------
        mix_id : str
            Mix identifier
        description : str
            Description
            
        Returns:
        --------
        str : Complete template
        """
        template = ""
        template += self.generate_input_header(mix_id, description)
        template += self.generate_system_definition()
        template += self.generate_phases_definition()
        template += self.generate_conditions_section()
        template += self.generate_bulk_composition_template()
        template += self.generate_gas_phase_template()
        template += self.generate_solver_options_section()
        
        return template
    
    def save_template(self, filename='gems_template.txt'):
        """
        Save template to file.
        
        Parameters:
        -----------
        filename : str
            Output filename
        """
        template = self.generate_full_template()
        
        output_path = config.INPUTS_TEMPLATES_DIR / filename
        with open(output_path, 'w') as f:
            f.write(template)
        
        print(f"✓ Template saved to: {output_path}")
        return output_path


def main():
    """Main function to generate template."""
    print("\n" + "=" * 80)
    print("Phase 3.1: xGEMS Template Generator")
    print("=" * 80 + "\n")
    
    # Create template generator
    template = GEMSTemplate()
    
    # Display system information
    print("System Components:")
    components = template.get_independent_components()
    print(f"  {len(components)} components: {', '.join(components)}")
    
    print("\nPhases:")
    phases = template.get_phase_list()
    for category, phase_list in phases.items():
        print(f"  {category}: {len(phase_list)} phases")
    
    all_phases = template.get_all_phases_flat()
    print(f"\n  Total phases: {len(all_phases)}")
    
    print("\nThermodynamic Conditions:")
    print(f"  Temperature: {template.temperature_k} K ({template.temperature_k - 273.15}°C)")
    print(f"  Pressure: {template.pressure_bar} bar")
    
    # Generate and save template
    print("\nGenerating template file...")
    output_path = template.save_template()
    
    # Display template preview
    print("\nTemplate preview (first 30 lines):")
    print("-" * 80)
    with open(output_path, 'r') as f:
        for i, line in enumerate(f):
            if i >= 30:
                print("...")
                break
            print(line, end='')
    print("-" * 80)
    
    print("\n" + "=" * 80)
    print("Template Generation: COMPLETE ✓")
    print("=" * 80 + "\n")
    
    return template


if __name__ == '__main__':
    template = main()
